### ISSUE TITLE
Review / Audit security & dependencies

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#111]
Prior to release, we should perform the following tasks to ensure we have a "clean" state:

- [x] Find tool for package dependency analysis
- [x] Check all dependencies (and minimize, where possible)
- [x] Validate repo security settings (dependabot, vulnerability scanning, ...)
- [x] Run security-related Linters across whole package

Ideas / tasks:

- [x] ~Consider replacing github.com/json-iterator/go with github.com/goccy/go-json everywhere (higher performance, implicitly included via gin, no release since 2021, _but_: Still seems to be more or less in beta)~
- [x] Enable `jsoniter` build tag for gin to use that framework (consistent with `httpc`): #186 
- [x] Get rid of github.com/labstack/echo and github.com/labstack/gommon (implicit dependency via fako1024/httpc)
- [x] Remove github.com/fatih/color and hence github.com/mattn/go-colorable + github.com/mattn/go-isatty (used only to format bold + color text in two places, which can be done trivially with one-liners)
- [x] Remove all usage of deprecated `io/ioutil` package and replace with recommended functions
- [x] Remove all remaining usage of `encoding/json` and replace with `jsoniter` 
- [x] Check for any new linter / deprecation warnings once moved to Go 1.21 (e.g. for array / slice casts)

In addition, golang.org/x/exp is going to be removed as part of https://github.com/els0r/goProbe/issues/137

**Comment by fako1024** [comment]
Ideas / tasks:

- [ ] Replace github.com/json-iterator/go with github.com/goccy/go-json everywhere (higher performance, implicitly included via gin)

**Comment by els0r** [comment]
The json plug sounds good. I can see that being performance relevant in the scope of the JSON output of goQuery and the results parsing of global-query

**Comment by fako1024** [comment]
> The json plug sounds good. I can see that being performance relevant in the scope of the JSON output of goQuery and the results parsing of global-query

Yeah, I'm just a little worried about it - The dependency is also implicit via `httpc`, so I'd have to replace it there, too. Unfortunately there seem to be quite a lot of open (and not very edge-case-y looking TBH) bugs in the codebase (looking at open issues + PRs, none of which have received attention for a couple of months now). Knowing that Nect uses the package excessively for JSON API parsing (including JSON generated by Python APIs) I'm unsure if I'd be creating a mess...

**Comment by fako1024** [comment]
@els0r Now this just got _very_ interesting. Looking at the implementation at https://github.com/gin-gonic/gin/tree/master/internal/json , gin includes _four_ different JSON implementations, triggered by respective build tags:

- `encoding/json`  (default)
- `goccy/go-json`
- `json-iterator/go`
- `bytedance/sonic`

And sure enough, when compiling `goProbe` as is, we indeed do not even use `goccy/go-json`:
```
# go build -a -v 2>&1 | grep "json"
encoding/json
github.com/json-iterator/go
github.com/gin-gonic/gin/internal/json
github.com/gabriel-vasile/mimetype/internal/json
```

This leads to the following conclusions:

1. We need to specify a build tag if we want gin to use anything other than the slow `encoding/json`.
2. On `go.mod` level we won't be getting rid of any of these implementations because they are _all_ in gin - BUT: only the one specified via build tag is used, so from a security point of view the surface is still minimized.
3. Given the beta status of `goccy/go-json` and the comments in my previous post I would suggest we use `json-iterator/go` using the `jsoniter` build tag (at least that's stable) for the time being, that way we minimize the number of dependencies while still gaining performance w.r.t. the current implementation. If `goccy/go-json` becomes more mature I'll be more than happy to switch to that.

Interesting, huh? What do you think?
