### ISSUE TITLE
API: config reload target

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#120]
Allow config hot reload via API.

* interfaces section only - all other fields require restart of goProbe
* incorporate into `config` and `config reload` command for `gpctl`

**Comment by els0r** [comment]
The changes introduced on the linked need looking into:

* they introduce deadlocks when updating config and shutting down goProbe

Noticed when testing the changes on develop:

* when interfaces removed, they aren't written out a last time. Only if Close is called on them. Disabled interfaces should _always_ be written to disk one last time
* the `runCtx` doesn't propagate the iface key
* the caller key is broken due to the update of the slog pacakge (fixed in 120)
* logfmt defaults to json (fixed in 120)

```
{"ts":"2023-05-19T04:40:35.749527834+02:00","level":"info","msg":"initializing capture / running packet processing","version":"devel"}
{"ts":"2023-05-19T04:40:35.750590193+02:00","level":"info","msg":"initializing capture / running packet processing","version":"devel"}
```

@fako1024 : regarding the removal of interfaces, I think we missed something in your recent PR. It's also why I changed the order in `cm.update` from `Enable -> Disable` to `Disable -> Enable`.

Would appreciate feedback on the current state of branch 120. Maybe you can spot where I introduce the deadlock(s) and if the approach even makes sense that way.

**Comment by fako1024** [comment]
> Would appreciate feedback on the current state of branch 120. Maybe you can spot where I introduce the deadlock(s) and if the approach even makes sense that way.

Sure. Quite simple, actually:

In line 266 of `capture_manager.go` you / we are locking it globally (to avoid concurrent calls to `update()`. However, in line 416 (in `performWriteout()` another lock is attempted. Unfortunately this function is now called _within_ the existing aforementioned lock, which in turn causes your deadlock)...

Shouldn't we just ensure that `Close()` is called on "disable" (because that will take care of everything) instead of trying to add a more complex workaround? After all there is no "disable" anymore. If an interface is removed, it should be closed (and the `Update()` method will take care of the rest), or am I missing something?

**Comment by els0r** [comment]
> > Would appreciate feedback on the current state of branch 120. Maybe you can spot where I introduce the deadlock(s) and if the approach even makes sense that way.
> 
> Sure. Quite simple, actually:
> 
> In line 266 of `capture_manager.go` you / we are locking it globally (to avoid concurrent calls to `update()`. However, in line 416 (in `performWriteout()` another lock is attempted. Unfortunately this function is now called _within_ the existing aforementioned lock, which in turn causes your deadlock)...

Thanks. I'll have a look at that again.

> 
> Shouldn't we just ensure that `Close()` is called on "disable" (because that will take care of everything) instead of trying to add a more complex workaround? After all there is no "disable" anymore. If an interface is removed, it should be closed (and the `Update()` method will take care of the rest), or am I missing something?

I do: the case when the parameters of an interface change that is already being captured on. It means that the interface has to go through the following stages

* write flows to disk
* disable capturing / close
* enable capturing with new parameters

Even though it is a pretty rare case, we should support it. Even more so, if we stick to the paradigm that the `Interfaces` section of the config supports hot-reload.

> 
> On second thought: Independent of that: Does the global counter / timer for the `LastRotation()` even make sense if a reload can trigger individual interfaces? From what I can tell it's only used in the API, but in fact it doesn't return what the name implies. Do we really need that or should we save ourselves the trouble? Alternatively I'd at least suggest we only increment / set the value upon _regular_ rotation via the scheduler (and / or if _all_ interfaces are rotated). What do you think?

I'm with you that it really doesn't add up on the per-interface side. To keep track of regular rotations of all interfaces (the common case), I would keep it in.
