### ISSUE TITLE
Potential race condition when closing capture(s)

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#126]
It seems that when shutting down `goProbe` there still is a race condition when closing / freeing a capture:
```
ts=2023-05-25T20:40:38.619+02:00 level=error msg="failed to free capture resources: cannot call Free() on open capture source, call Close() first" version=devel iface=eth1
```

First identified here: https://github.com/els0r/goProbe/pull/122#discussion_r1203676129

**Comment by fako1024** [comment]
Based on an initial analysis it seems that contrary to my assumption the check for an open file descriptor is _not_ atomic:
```
// IsOpen determines if the file descriptor is open / valid
func (sd FileDescriptor) IsOpen() bool {
	_, err := unix.FcntlInt(uintptr(sd), unix.F_GETFD, 0)
	return err == nil
}
```
While definitively being closed in `Close()`, the `IsOpen()` check in `Free()` (which is called from a different goroutine) is not guaranteed to observe that... :roll_eyes:

**Comment by fako1024** [comment]
After some consideration I have decided to move the `Free()` logic into the `Close()` method. That way:

- The aforementioned conundrum is gone (since the `process()` routine doesn't have to take care of `free()`ing the resources from a different goroutine)
- The interface / code is simplified (no more `Free()`)
- The behavior is more intuitive (when `Close()` returns, the capture is closed, period)

**Comment by fako1024** [comment]
@els0r FYI (had nothing to do with your changes in #120).

**Comment by els0r** [comment]
Many thanks for looking into it. From a user perspective, it makes sense that a Close() would also release the resources under the hood.
