### ISSUE TITLE
Logging configuration not (fully) taken into account

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#128]
It seems that at present, at least parts of the logging config is not taken into account (by the `CaptureManager` I suspect) since if I instantiate a new manager, e.g. via the E2E test like this:
```
captureManager, err := capture.InitManager(ctx, &config.Config{
		DB: config.DBConfig{
			Path:        tempDir,
			EncoderType: encoders.EncoderTypeLZ4.String(),
			Permissions: goDB.DefaultPermissions,
		},
		Interfaces: ifaces,
		Logging: config.LogConfig{
			Destination: "logfmt",
			Level:       "error",
		},
	}, capture.WithSourceInitFn(func(c *capture.Capture) (slimcap.SourceZeroCopy, error) {
		mockSrc, err := afring.NewMockSource(c.Iface(),
			afring.CaptureLength(link.CaptureLengthMinimalIPv6Transport),
			afring.Promiscuous(false),
			afring.BufferSize(1024*1024, 4),
		)
		require.Nil(t, err)
		return mockSrc, nil
	}))
```
`INFO` level messages are still thrown to the console:
```
2023/06/06 13:58:52 INFO initializing capture / running packet processing
2023/06/06 13:58:52 INFO initializing capture / running packet processing
2023/06/06 13:58:52 INFO waiting for 1m8s to start capture rotation
2023/06/06 13:58:52 INFO initializing capture / running packet processing
2023/06/06 13:58:52 INFO initializing capture / running packet processing
2023/06/06 13:58:52 INFO waiting for 1m8s to start capture rotation
2023/06/06 13:58:52 INFO initializing capture / running packet processing
2023/06/06 13:58:52 INFO initializing capture / running packet processing
```

**Comment by fako1024** [comment]
I also noticed that the structured fields seem to be incoherent, e.g. in `capture.go`:
```
ctx = logging.WithFields(ctx, slog.String("iface", c.iface))
logging.FromContext(ctx).Info("initializing capture / running packet processing")
```
Emits this (`logfmt`):
```
{"ts":"2023-06-07T09:59:37.524638686+02:00","level":"info","msg":"initializing capture / running packet processing","version":"872abf81"}
```

So it seems to have the version from the calling context, but is missing the (supposedly) added `iface` field. @els0r : Just to be safe: This shouldn't happen, right?

**Comment by fako1024** [comment]
Interesting, when changing:
```
ctx = logging.WithFields(ctx, slog.String("iface", c.iface))
```
to
```
ctx = logging.WithFields(ctx, "iface", c.iface)
```
it works like a charm. Looking at the `FromContext()` implementation it seems that it simply fails to read the attribute created by `slog.String()`, but does so silently. The reason it fails is simply because `WithFields()` excludes this:
```
	// ignore malformed fields as the logging implementation wouldn't accept them anyhow
	if !(len(fields) >= 2 && (len(fields)%2 == 0)) {
		return ctx
	}
```

**Comment by els0r** [comment]
Thanks for bringing it up and independently verifying something I realized a while back: the `WithFields` part isn't consistent with what we can provide to the `slog` logger.

My approach would be to actually go a bit stricter on it and enforce the use of `slog.Attr` fields when calling `WithFields`. So changing the function signature. I would say the consistency outweighs the benefit of stuffing any key-value pair into the function call.
