### ISSUE TITLE
Config handling causes panic

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#132]
The way the configuration is currently handled / validated can in at least one case cause a panic (run against current `develop`):
```
panic: value method github.com/els0r/goProbe/cmd/goProbe/config.APIConfig.validate called using nil *APIConfig pointer

goroutine 1 [running]:
github.com/els0r/goProbe/cmd/goProbe/config.(*APIConfig).validate(0x91a280?)
	<autogenerated>:1 +0x9d
github.com/els0r/goProbe/cmd/goProbe/config.(*Config).Validate(0xc000098100)
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goProbe/config/config.go:236 +0x130
github.com/els0r/goProbe/cmd/goProbe/config.Parse({0xa32ac0, 0xc0000140e0})
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goProbe/config/config.go:275 +0x239
github.com/els0r/goProbe/cmd/goProbe/config.ParseFile({0x7ffd277c6570?, 0x188?})
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goProbe/config/config.go:254 +0xa8
main.main()
	/home/fako/Develop/go/src/github.com/els0r/goProbe/cmd/goProbe/goProbe.go:55 +0x12f
```

-> I didn't have an `api` subconfig set. Aside from the fact that this should be valid (because I didn't want to enable the API) it should definitively not panic.

DoD

- [x] Cross-check all existing config parameters for consistent handling of invalid input
- [x] Ensure optional config fields / objects can be omitted
- [x] Add / extend tests to ensure correct handling

**Comment by fako1024** [comment]
@els0r Can you maybe take a shot at this?

**Comment by fako1024** [comment]
Also sidenote: I just saw that `gin` is running in debug mode, doesn't seem to warrant a new issue for that, but maybe we should switch that to `gin.SetMode(gin.ReleaseMode)` (or maybe couple it to the configured log level of `goProbe`)?

**Comment by els0r** [comment]
Huh? I thought I had fixed this. Will have a look for sure.

Agree on the gin thing as well. Will just set it to `Release`. Who cares about those debug messages anyhow.

**Comment by els0r** [comment]
Will be fixed in branch https://github.com/els0r/goProbe/tree/132-config-handling-causes-panic. WIP, but ripping out the `testdata` and working with structs for the tests instead.

Will add more tests in upcoming commits.
