### ISSUE TITLE
Adapt Logger (slog) dependency to Go instrinsics

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#137]
As of Go 1.21, `slog` is now part of the core library (see https://tip.golang.org/doc/go1.21), so we should probably switch the dependency to that (and enforce Go >= 1.21 in `go.mod`).

DoD

- [x] Once available, update to Go 1.21 (and enforce in `go.mod`)
- [x] Switch `slog` dependency to core library

**Comment by els0r** [comment]
This happened quicker than I thought. Glad we are prepared already.

**Comment by fako1024** [comment]
@els0r FYI: Go 1.21 just got released, so once the OSAG build pipeline is updated you should be good to go!

**Comment by fako1024** [comment]
@els0r Would it help you if I do the replacement? We can keep the branch until OSAG is ready for it. Just let me know / re-assign if I can save you some time / trouble...

**Comment by els0r** [comment]
> @els0r Would it help you if I do the replacement? We can keep the branch until OSAG is ready for it. Just let me know / re-assign if I can save you some time / trouble...

Thanks a lot for asking. That would really help, yes.
