### ISSUE TITLE
Document v4 in README

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#147]
Refresh docs:

- [x] @els0r : goProbe documentation -> link to the individual tools, link to slimcap 
- [x] Provide commented example of configuration (outlining what's optional etc.)
- [x] @fako1024 : docs for legacy tool
- [x] @fako1024 : slimcap docs

**Comment by fako1024** [comment]
@els0r A side note on the OpenAPI stuff: `httpc` supports in-fliight validation of all requests against an OpenAPI spec. I don't think it's efficient to build that into the client for all requests (after all, we control that) but it could come in handy for future testing (added that to #187 ).
I'm also reopening this one for me to finish my item (slimcap documentation) today.

**Comment by fako1024** [comment]
Slimcap documentation taken care of in this PR: https://github.com/fako1024/slimcap/pull/68
