### ISSUE TITLE
Add profiling options to goQuery

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#168]
I just realized that goQuery does not have a profiling parameter / option (in the past I've always added it manually to the code whenever I wanted to make assessments). In the light of supporting PGO (and also for debugging / performance measurements) I think it would be prudent to add an option similar to what we had for goProbe before it was replaced with the API level profiling (as in: one parameter for a profile directory, triggering both CPU and memory profile output for the goQuery invocation).

**Comment by fako1024** [comment]
@els0r Do you concur?

**Comment by els0r** [comment]
Absolutely. Every binary should be able to produce a profile, except gpctl. There it really is only a convenience wrapper.
