### ISSUE TITLE
Factor out buffer pools and bitpack modules

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#171]
In order to reuse them in other projects (without having to include the whole `goProbe` repo) I'd like to move the buffer pool and bitpack implementations to the monorepo at https://github.com/fako1024/gotools (as individual sub-packages, so they can be included without introducing dependencies on other elements of said repo). In addition to being reusable I think these two modules are not in good places right now anyway (`bitpack` is not an encoder in the sense of fulfilling that interface and the two buffer pools don't really belong in `gpfile` IMHO)...

@els0r Would that be OK for you?

DoD

- [x] Transfer `bitpack` from `encoder` to `gotools/bitpack`
- [x] Transfer buffer pools from `gpfile` to existing `gotools/concurrency`
- [x] Enable dependabot, CodeQL and all other repo management features for `gotools`
- [x] Migrate package references to `gotools` repo and cleanup intrinsic code

**Comment by els0r** [comment]
As discussed: by all means. No need for copy-pasta in other projects :)
