### ISSUE TITLE
Extend goProbe / global-query API to provide alternative query methods

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#185]
Currently, the API supports only a `POST` to `_query` using the query arguments as JSON body. While being clean and idiomatic (because we can simply juggle around with structs) it ~may~ does not fulfill all use cases.
In particular, when writing a pipeline / processing flow for goProbe using Graylog I came across a rather common limitation: The tool can only perform `GET` queries using form / query parameter (or header) encoding.

In addition, I realized that there are a few parameters (`num_results` and `max_mem_pct`) which seem to be required via the API although they have reasonable defaults so I suggest to set these defaults (making the number of required arguments for a query a little more lean).

DoD

- [x] Remove requirement for `num_results` and `max_mem_pct` in API (use defaults)
- [x] Provide a `GET` route (can be the same path, since `GET` is not in use yet) with alternative means of setting query arguments (URL parameters or headers)
- [x] Add global (not per-IP) rate limit for query calls to allow preventing a "Query-(D)DOS" of the actual sensor hosts
- [x] Support adding live data to queries via API

**Comment by fako1024** [comment]
@els0r Would like your input on this one. On the plus side: Hacking around on a local instance I was already able to direct a simple conditional query from our Graylog instance to goProbe and parsing the JSON result which should be 75 % of the required effort already. As I hinted in the description having the aforementioned functionality would be a requirement to make it work though...

**Comment by els0r** [comment]
Sounds perfectly reasonable since it simply provides a different entrypoint to the same kind of processing.

Let's do with the form annotations.

**Comment by fako1024** [comment]
@els0r Works like a charm (for both `goProbe` and `global-query`, I tested both via the existing JSON and form-data requests, see PR for changes.

As for feedback, I encountered two things (one of which being a blocker for the Graylog implementation, the other merely cosmetic in nature):

- Right now there does not seem to be a way to query _all_ hosts defined in the querier config, so I always have to specify an explicit list of hostnames to run the query on. While being very safe (in particular seeing where you are coming from - you don't want to accidentally fire off a query to a couple of thousand hosts implicitly) this doesn't seem hyper-practical for "the common person". In this case the tool simply doesn't know (and doesn't have to) which hosts will be available to the `global-query` API, that is exactly what the config with its explicit list already accomplishes (or can accomplish). So I think we should provide a way (could even be guarded by a new, explicit API argument / parameter to avoid accidental use) to simply fire off the query to all hosts configured for the querier.
- I've struggled a bit with the naming of `HostQuery`. My guess is that it's driven by the `gethosts` concept. I assume you are planning to embed that into the query so you can build up the list in line. Makes total sense, but again the average jane / joe doesn't have such tools at their disposal and might not understand (Even I was unsure if that was meant to be a different query or whatever, in particular because there's another argument called "hostname"). So maybe we could rename that struct element / variable to something more universal (like: `HostList` or `QueryHostList` or whatever)? Just a thought.

What are your thoughts about these points?

**Comment by fako1024** [comment]
@els0r : I added a global rate limiter for `goProbe` in commit 73c6b2f (otherwise it would be trivially easy to kill the host it runs on by simply triggering whatever rule performs the queries and hence hammering it with 1000s of requests per second, all running CPU & I/O on the actual sensor host).

**Comment by fako1024** [comment]
@els0r And one last sweet feature (last commits): Given the new locking mechanism and all I've added the (again, optional) ability to add the live data (flows currently available in the flowMap that are not yet written) to a query (of course only available via `goProbe` API since `goQuery` does not have access to the `CaptureManager`). I really love that because a) it was really easy to implement with our new package structure and b) it allows some really amazing thing for the Graylog interface (because when you trigger a lookup in `goProbe` you can now see _all_ data, which in practice is of course the most important / interesting stuff when you trigger a lookup by e.g. some suspicious traffic pattern)...
And as cherry on top I've added a cross-check of all data being captured in the E2E test with the data accessed via `goQuery` (by grabbing the "live" flows just before shutting down `goProbe` (which are, well, all flows) and then comparing them with all seen flows.

**Comment by fako1024** [comment]
Moved outstanding questions as non-blocking to #187
