### ISSUE TITLE
global-query: support plug-in structure for querier

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#226]
The `Querier` and `Resolver` interfaces have been defined to allow people to use and compile their own implementations to fetch `results.Result` from a sensor fleet.

The way that global-query is currently set up, there's no way to plug those implementations in, however.

*Note*: a separate issue will be created for the `Resolver` when the need arises.

# Some Conventions

* only one querier plugin and host resolver can be enabled at any given time
* changing plugins requires a restart of the server
* all plugins are stored in `pkg/distributed/contrib`
* all plugins MUST be able to configure themselves from a config file
* the plugin list MUST be provided via imports, from a file with the `contrib` flag set
* plugins must be built using the `contrib` tag

DoD:

- [x] support registration of Queriers
- [x] set up `contrib` directory

**Comment by fako1024** [comment]
Will take a look at conditional contribution / third-party ingestion in Go modules asap and provide billo - template for further implementation...
