### ISSUE TITLE
Querier interface: redefine to support streaming results

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#228]
Base interface should return a `<- chan *results.Result` so we don't block ourselves from supporting the `raw` streaming case.

This will condense the following lines in `global-query`:

```golang
	finalResult := aggregateResults(ctx, stmt,
		runQueries(ctx, numRunners,
			prepareQueries(ctx, q.querier, hostList, &queryArgs),
		),
	)
```

Where `runQueries` and `prepareQueries` will likely move into the `Querier`.

**Comment by fako1024** [comment]
@els0r I don't think this is required anymore, given the changed approach in #213 that doesn't need a streaming interface, but instead required the client implementation to perform bulk requests. Do you agree or am I missing something here (in which case feel free to re-open).

**Comment by els0r** [comment]
> @els0r I don't think this is required anymore, given the changed approach in #213 that doesn't need a streaming interface, but instead required the client implementation to perform bulk requests. Do you agree or am I missing something here (in which case feel free to re-open).

I fully agree.
