### ISSUE TITLE
goQuery 'list' target is slow on sensors with many interfaces

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#282]
Due to the way we currently handle the list target (we basically mimic an actual query for data to figure out which interfaces exist) the `list` target doesn't scale very well if there's a lot of interfaces (which we know can happen). We should re-evaluate if the target can be sped up.

DoD

- [x] Revisit current implementation
- [x] Optimize or re-implement (e.g. by dedicated flow for list target instead of data access)

**Comment by fako1024** [comment]
A quick analysis / profiling session shows the following:

- Even for a _really_ large tree the actual CPU cycles used are not an issue (about 2s overall for a DB with two months worth of 600 interfaces). There are probably a few improvements possible though (but that won't help much, see next item)
- In order to ascertain the traffic information we are performing an access to the `.blockmeta` file of each `GPDir`, so in this case 600*60 = 36000 disk accesses

On a system with an SSD these random seeks are causing a little bit of overhead (overall runtime is about 5s, which is still acceptable), but on a system with a spinning disk these are probably pure horror...

**Comment by els0r** [comment]
> A quick analysis / profiling session shows the following:
> 
> * Even for a _really_ large tree the actual CPU cycles used are not an issue (about 2s overall for a DB with two months worth of 600 interfaces). There are probably a few improvements possible though (but that won't help much, see next item)
> * In order to ascertain the traffic information we are performing an access to the `.blockmeta` file of each `GPDir`, so in this case 600*60 = 36000 disk accesses
> 
> On a system with an SSD these random seeks are causing a little bit of overhead (overall runtime is about 5s, which is still acceptable I guess), but on a system with a spinning disk these are probably pure horror...
> 
> We could do the following:
> 
> * Change the output of the `list` target to not include the volumes from the metadata (basically just show the time ranges, which would only require metadata access for the first and last directory of each interface)
> * Provide the existing functionality as an extra target or via a command line argument (whatever feels best), e.g. `list-traffic` or `--traffic list` or `--details list` or ...
> 
> This would basically cover all use cases, the "cheap" call would tell the user what data is available for which interface (enough for most cases because it answers the question: "was `goProbe` capturing data on an interface at a certain point in time") and the more detailed one provides an idea of how much traffic was captured for each interface (without having to come up with a dummy query).
> 
> @els0r Do you concur?

I concur. Most of the times we want to know which interfaces are available for querying.

We already have the `--detailed` flag for the list target. With your proposal, we could just shift the traffic calculation into the detailed target instead.

**Comment by fako1024** [comment]
As discussed: Change of scope. We will provide an adjacent data structure on a per interface basis (so at the top of the directory interface) that will contain the global stats _without replacing any current metadata concept_. Details TBD.

**Comment by fako1024** [comment]
After re-implementing this using a symlink with embedded metadata for each directory these are the preliminary numbers in comparison (OS caches dropped / flushed in between):
```
## OLD
└─ $ ▶ time ./goQuery  -d /home/fako/Downloads/goProbe/db_many list 2>&1 > /tmp/out.txt
real	0m5.090s
user	0m1.738s
sys	0m1.084s
```

```
## NEW
└─ $ ▶ time ./goQuery  -d /home/fako/Downloads/goProbe/db_many list 2>&1 > /tmp/out.txt
real	0m0.527s
user	0m0.161s
sys	0m0.111s
```

So a performance increase of about a factor of 10. :heart:
