### ISSUE TITLE
Support for regex in the `query.Args.Interfaces` argument

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#342]
### Problem Statement

Currently, the `Interfaces` argument in `query.Args` supports

- a single interface
- a comma-separated list of interfaces (all of which must exist)
- any interface (which takes all interfaces which were parsed in the DB)

An intermediate layer is missing: the ability to arbitrarily slice the set of all interfaces in the DB. When preparing the query statement, those interfaces pertaining to a given Regex pattern are selected for query.

### Examples

```
-i "eth[0-4]"
```
as the equivalent of `eth0,eth1,eth2,eth3,eth4. Or

```
-i "tun_4.*"
```

to select all IPv4 tunnels on the system (provided the interfaces are all prefixed with `tun_4`.

### Implications for `global-query`

They are far-reaching. Every sensor getting a regex interface argument can decide for itself which interfaces are part of the query (just like it's done for `any`).

**Comment by fako1024** [comment]
Addendum: As discussed it may also be nice to support a simple negation of interfaces (in addition to the regex logic), as in:
```
-i any,!eth0,!eth1
```
to mean `any` interface, but not `eth0` or `eth1`. More complicated negation can then be done via the regex magic...

**Comment by fako1024** [comment]
Closed with #344
