### ISSUE TITLE
Support PF_RING

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#35]
Since gopacket supports the PF_RING module (see https://www.ntop.org/products/packet-capture/pf_ring/), we might consider supporting it via goprobe as well (refer to https://pkg.go.dev/github.com/google/gopacket/pfring for how to use it within the context of gopacket).
This way, we could support high-traffic scenarios without being limited to libpcap (which will, at some point, start dropping packets if rates get too high).
Ideally, we would support both capturing via libpcap and PF_RING without build constraint, but I'm unsure if that's possible (I wasn't yet able to test the module due to my Kernel being too new, see https://github.com/ntop/PF_RING/issues/817).

**Comment by els0r** [comment]
I have an am testing the module with pf_ring at the moment. See PR for #34.
