### ISSUE TITLE
Improved map key & in-memory data structure concept

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#44]
After doing some tests as part of #37 it might be beneficial to revamp the internal data structures, in particular the in-memory flow aggregation map(s) (which uses an expensive struct key right now and is not very flexible). General idea would be to replace the map key by a string and then use raw data bytes (with string casts where required) all the way from capture until the moment information needs to be formatted for the user. Expected advantages:

- Fewer allocations due to reduced number of conversions / struct population
- Less time spent on map hashing (since a simple string can be hashed faster than a composite key), which currently is one of the most CPU consuming tasks for larger queries
- More flexibility w.r.t. to keying, e.g. IPv4 vs. IPv6 traffic (could save space both in-memory and on-disk
- More straight-forward data storage / retrieval (essentially just handling byte slices instead of copying forth and back between structs and bytes)

**Comment by fako1024** [comment]
First shot looks promising, reduces DB size by an additional 7% due to IPv4/IPv6 handling) and allocations during query by about 15%:
 `   
Showing nodes accounting for 580.49MB, 98.18% of 591.23MB total
Dropped 17 nodes (cum <= 2.96MB)
Showing top 10 nodes out of 26
      flat  flat%   sum%        cum   cum%
  229.45MB 38.81% 38.81%   237.45MB 40.16%  github.com/els0r/goProbe/pkg/goDB/storage/gpfile.(*GPFile).ReadBlock
  211.34MB 35.75% 74.55%   526.48MB 89.05%  github.com/els0r/goProbe/pkg/goDB.(*DBWorkManager).readBlocksAndEvaluate
   52.25MB  8.84% 83.39%    86.30MB 14.60%  github.com/els0r/goProbe/pkg/goDB/storage/gpfile.(*GPFile).readHeader
   36.40MB  6.16% 89.55%    36.40MB  6.16%  github.com/els0r/goProbe/pkg/query.aggregate.func1
   13.50MB  2.28% 91.83%    13.50MB  2.28%  fmt.newScanState
   12.98MB  2.20% 94.03%    26.13MB  4.42%  github.com/els0r/goProbe/pkg/query.(*Statement).Execute
`
-->
`Showing nodes accounting for 462.70MB, 96.30% of 480.46MB total
Dropped 5 nodes (cum <= 2.40MB)
Showing top 10 nodes out of 33
      flat  flat%   sum%        cum   cum%
  195.01MB 40.59% 40.59%   428.33MB 89.15%  github.com/els0r/goProbe/pkg/goDB.(*DBWorkManager).readBlocksAndEvaluate
  146.08MB 30.40% 70.99%   159.10MB 33.11%  github.com/els0r/goProbe/pkg/goDB/storage/gpfile.(*GPFile).ReadBlock
   52.24MB 10.87% 81.87%    77.77MB 16.19%  github.com/els0r/goProbe/pkg/goDB/storage/gpfile.(*GPFile).readHeader
   22.29MB  4.64% 86.51%    22.29MB  4.64%  github.com/els0r/goProbe/pkg/query.aggregate.func1
   13.48MB  2.81% 89.31%    27.61MB  5.75%  github.com/els0r/goProbe/pkg/query.(*Statement).Execute
    9.50MB  1.98% 91.29%     9.50MB  1.98%  fmt.newScanState
`

And as expected we now spend less time with map key calculations (making heavy use of `runtime.mapaccess2_faststr()` instead of `runtime.mapaccess2()`). Will have to do some proper benchmarks and maybe some minor improvements with a larger DB though (right now there's not much difference in comparison to the time spent working on the metadata).
goProbe yields identical results as well. goConvert is currently broken, will have to fix that. The generalized StringParser stuff really is tricky when it comes to flexible key sizes...

**Comment by fako1024** [comment]
@els0r : If you have a moment it would be cool if you could give this a shot on an OSIX host (running goProbe + conversion from legacy + some queries) from the attached branch. As mentioned above I don't expect much speedup right now, but your scenario is more realistic than mine and you've already played around with query timings over the last days... Thanks a lot!

**Comment by fako1024** [comment]
Further reduction of memory allocated during query by another ~25% by simple means of re-usable memory buffers for GPFile (which cannot be used concurrently anyways) (https://github.com/els0r/goProbe/commit/092d302021c5a629d5a227c47dd4237ff6a1b271):
```
Showing nodes accounting for 323.11MB, 91.31% of 353.86MB total
```

**Comment by els0r** [comment]
> Further reduction of memory allocated during query by another ~25% by simple means of re-usable memory buffers for GPFile (which cannot be used concurrently anyways) ([092d302](https://github.com/els0r/goProbe/commit/092d302021c5a629d5a227c47dd4237ff6a1b271)):
> 
> ```
> Showing nodes accounting for 323.11MB, 91.31% of 353.86MB total
> ```

I'd say that's a fair argument for changing the interface :). Impressive!

**Comment by els0r** [comment]
> @els0r : If you have a moment it would be cool if you could give this a shot on an OSIX host (running goProbe + conversion from legacy + some queries) from the attached branch. As mentioned above I don't expect much speedup right now, but your scenario is more realistic than mine and you've already played around with query timings over the last days... Thanks a lot!

Preliminary (pretty much fresh out the oven) results are in. Size:
```
### 2018 build 
990M	db
### pre `#44`
707M	db-v4-2ba9266e/
### `#44` 
652M	db-v4-092d3020/
```
That's a whooping 35% reduction in disk space for a DB encompassing 6 months of data spanning a captured traffic volume of 11.7 TB.

Now to the ugly
### 2018 build 
Query stats          : 2.34 M hits in 3.9s
### pre `#44`
Query stats          : displayed top 5 hits out of 2.37 M in 4.9s
### `#44`
```
panic: runtime error: index out of range [0] with length 0

goroutine 38 [running]:
github.com/els0r/goProbe/pkg/goDB.ExtendedKey.IsIPv4(...)
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goDB/keyval.go:206
github.com/els0r/goProbe/pkg/goDB.ExtendedKey.Key(...)
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goDB/keyval.go:198
github.com/els0r/goProbe/pkg/goDB.genCopyToKeyFns.func4(0xc0006129f0?, {0x0?, 0x80e348?, 0x80e350?}, {0xc000178000?, 0x0?, 0x372c3933352c3336?})
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goDB/DBWorkManager.go:235 +0xd6
github.com/els0r/goProbe/pkg/goDB.(*DBWorkManager).readBlocksAndEvaluate(0xc00007f2c0, {0x85c3c0, 0xc0000286c0}, {0xc000133600, {0xc00017ddaa, 0xa}, {0xc0003a8000, 0x120, 0x200}}, 0xc00022e000)
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goDB/DBWorkManager.go:368 +0x195c
github.com/els0r/goProbe/pkg/goDB.(*DBWorkManager).grabAndProcessWorkload.func1()
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goDB/DBWorkManager.go:178 +0x20a
created by github.com/els0r/goProbe/pkg/goDB.(*DBWorkManager).grabAndProcessWorkload
	/usr/src/packages/src/sdwan/security/pkg/OSAGtmi/goProbe/pkg/goDB/DBWorkManager.go:160 +0xea
```

Query args for all three cases. Spans `Timespan / Interface : [2022-08-08 01:55:06, 2023-02-01 21:33:44] / lacp0`
```
-c "dport != 5551" -i lacp0 -f -300d -l '2023-02-01 21:33:44' -n 5 sip,dip,dport,proto
```

**Comment by fako1024** [comment]
Thx. Will check out the issue, more changes incoming anyway. The warnings are expected, same here. Will probably demote to INFO...

**Comment by fako1024** [comment]
Last commit incorporates significant performance improvements implemented over the last days. Numbers first:
```
develop
---------------------------------
DB Size on disk:        1084276 kiB
Max resident memory:     875732 kiB
Query runtime:            09.68 s
CPU time:        (22.81 + 2.91) s
Allocation size:           8.10 GiB
Allocated objects:     28068232

latest commit (028b647ddd652fa710813f565461f46695baf7cb)
---------------------------------
DB Size on disk:        1009792 kiB (- 7 %)
Max resident memory:     667836 kiB (-24 %)
Query runtime:            07.63 s   (-21 %)
CPU time:        (15.86 + 1.57) s   (-32 %)
Allocation size:           3.47 GiB (-67 %)
Allocated objects:     28262163     (+ 1 %)

latest commit (028b647ddd652fa710813f565461f46695baf7cb) - low mem mode
---------------------------------
DB Size on disk:        1009792 kiB (- 7 %)
Max resident memory:     591268 kiB (-32 %)
Query runtime:            07.75 s   (-20 %)
CPU time:        (16.22 + 2.65) s   (-27 %)
Allocation size:           3.37 GiB (-69 %)
Allocated objects:     28279884     (+ 1 %)
```

Enhancements:

- [ ] Switch to []byte keys and replacement of unneeded struct data duplication with simple memcpy operations  
- [ ] Implemented modified hashmap (based on the native Go implementation):
- [ ] -> Support []byte slices as keys (without conversion and zero-copy)
- [ ] -> Support single-op find-and-update instead of get-update-set
- [ ] -> Implement different map hash algorithm optimized for the use case of small byte slices
- [ ] -> Support in-place value updates of existing entries in the map without having to allocate a new Value struct
- [ ] Added shared memory pool for concurrent reading from GPFiles
- [ ] Added abstract in-memory structure for files that will be read completely anyway to reduce disk seeking by 3 orders of magnitude
- [ ] Added low-memory mode that disables memory pools and full reads (can be switched on by command line parameter)
- [ ] Added per-GPFile re-usable buffers and support provisioning of external buffers for re-use
- [ ]  Independent handling of IPv4 and IPv6 flows during query and segregated storage inside the respective file on disk to optimize memory usage and reduce file size on disk
- [ ] Moved `goDB.Key` and `goDB.Val` to `types` package to be less dependent and prone to import cycles

Fixes:

- [ ] Fix the conditional bug mentioned in @els0r 's last comment
- [ ] Removed unnecessary warnings about broadcasts having mismatched IPv4/IPv6 data during legacy file conversion
- [ ] Fixed various linter warnings

TODOs:

- [ ] Currently, the map causes quite a lot of garbage collection due the way maps work in Go (not limited to this custom map, it's actually even worse for the default Go map). Keys and values are stored as pointers inside the map, which for our huge aggregation maps causes >10% CPU time spent on GC (not even taking into account the number of allocations required). Now that we have a custom map this could be improved by means of flat slices as "storage" for keys and values (and instead of pointers use the indexes to reference them). This should be possible, but is a bigger task for later (outside of this branch / issue).
- [ ] We need a concept for the new cross-host fields `Hostname` and `HostID`. For various reasons it's not feasible / economical to always carry them in the `ExtendedKey`. A cheap approach would be to just wrap yet another Key around it (which is still a []byte slice and hence can still be used with the map), but maybe we can have a chat about that @els0r (since TBH I'm still not sure where these actually come into play).
- [ ] Test this on a spinning disk system. All numbers have been taken on a device with an SSD. I'd assume that some improvements could have even bigger impact on a system with an HDD.

**Comment by els0r** [comment]
The results surely don't lie that the performance improvements are significant. Tested with a DB that comprises only one interfaces and has a total of 43M flows (6.50 TB traffic).

| version | db size | query args | timing |
|---------|-----|-----------|--------|
| 2018 | 847M | `-f '2022-09-01 00:00' -l '2023-01-31 00:00' -i eth1 -c "dport != 5551" -n 5 sip,dip,dport,proto` | 288.55 k hits in 9.7s (3.3s upon repeating query) |
| de1581f | 574M | `-f '2022-09-01 00:00' -l '2023-01-31 00:00' -i eth1 -c "dport != 5551" -n 5 sip,dip,dport,proto` | displayed top 5 hits out of 288.55 k in 1.7s |

Not only is the DB 32% smaller, the large query spanning almost half a year also runs 49%-**81%** faster than the 2018 version.

Results are identical btw, so no loss of data observed.

**Comment by fako1024** [comment]
Thanks a lot for checking, that's even better than expected! As for your observation, could you let me know the exact query you did (`iface,sip,dip,dport,proto`, any conditionals like above)? I'd like to check if that's maybe some special path / constellation that doesn't benefit as much as it could. That being said, I'd assume that a) the `.meta` files are indeed one thing that is more prominent here, but I would expect that (trivialized statement) the more you add to the key, the less the difference between the version will become, for multiple reasons:

- The more key "entropy", the more individual entries in the intermediate and final maps, i.e. garbage collection gets worse and worse due to the map structure, so it matters less how much "better" the map is.
- Following the same argument, you profit less times for the fast path for updating the map entry in place (simply because you have to create new entries more often, relatively speaking), so you have less gains there as well.
-  It _could_ be that the hasher I used for the hashmap gets worse with higher key lengths than I expected. I'll take a look and compare the time spent on hashing and maybe will revisit.

But yeah, the `.meta` files are a low hanging fruit for sure...
