### ISSUE TITLE
Replace gozstd with zstd system library (in line with lz4) 

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#56]
We are currently using gozstd as primary zstandard implementation / package. Under the hood, it ships statically compiled libraries for all architectures. Along the lines of what we recently did with lz4 I propose to switch the zstd implementation in the same manner. That way we are independent of statically compiled components and have a unified way of interacting with these C libraries.
Since both use standard C libraries without customization I assume there will be no performance impact (but potentially even better access to parameters like block sizes and / or checksum control).

DoD

- [x] Replace gozstd with direct link into system-wide libzstd (similar to lz4 interface)
- [x] Attempt to re-use compressor / decompressor to avoid repeated context allocation
- [x] Provide global NullCompressor for shared use (at it isn't context aware / just a wrapper around `copy()`
- [x] Perform some tests / benchmarks

**Comment by fako1024** [comment]
@els0r What do you think? Sound good to you?

**Comment by els0r** [comment]
> 

Yup. I'm in. Also because the `zstd` OSIX package already exists, making building easier "internally" 😄

**Comment by fako1024** [comment]
First attempts look good, code replacement wasn't an issue. Interestingly I'm seeing a slight reduction in throughput performance during benchmarks. I'm quite sure though this is attributable to the fact that gozstd uses a context pool instead of creating a new one for each compression cycle.
That in turns leads me to believe that we can boost performance for lz4 by reusing contexts as well. I'll look into it tomorrow.

**Comment by els0r** [comment]
> 

Very nice. By context pool you are alluding the context in `C`-land, correct?

**Comment by fako1024** [comment]
Yeah, exactly, no matter if using the `ZSTD_compress()` or `ZSTD_compress2()` (a.k.a. with context) API a context is freshly created (similar concept for LZ4), which is something that we can avoid, either by pooling or by assigning a reusable compressor in the worker pipeline (because they run sequentially)...

**Comment by fako1024** [comment]
Running some benchmarks for comparison. Aside from that, the changes in handling of compression context and adding some more reusable memory buffers has the following impact (w.r.t. `develop`):
```
Max resident memory:     591460 kiB ( ±0 %)
Query runtime:            02.50 s   ( -8 %)
CPU time:         (6.55 + 0.67) s   (- 8 %)
Allocation size:           1.38 GiB (- 5 %)
Allocated objects:       258046     (-33 %)
```

**Comment by fako1024** [comment]
Benchmarks compression:
```
                             │ /tmp/old.out │             /tmp/new.out             │
                             │     B/s      │     B/s       vs base                │
LevelsCompress/lz4-lvl-1-4     191.4Mi ± 1%   192.2Mi ± 0%        ~ (p=0.072 n=10)
LevelsCompress/lz4-lvl-2-4     191.0Mi ± 1%   191.8Mi ± 1%   +0.43% (p=0.002 n=10)
LevelsCompress/lz4-lvl-3-4     34.00Mi ± 2%   34.08Mi ± 0%        ~ (p=0.066 n=10)
LevelsCompress/lz4-lvl-4-4     34.09Mi ± 0%   34.10Mi ± 0%        ~ (p=0.930 n=10)
LevelsCompress/lz4-lvl-5-4     34.03Mi ± 0%   34.09Mi ± 0%        ~ (p=0.127 n=10)
LevelsCompress/lz4-lvl-6-4     34.08Mi ± 0%   34.10Mi ± 0%        ~ (p=0.425 n=10)
LevelsCompress/lz4-lvl-7-4     34.08Mi ± 1%   34.11Mi ± 0%        ~ (p=0.643 n=10)
LevelsCompress/lz4-lvl-8-4     34.07Mi ± 0%   34.05Mi ± 0%        ~ (p=0.956 n=10)
LevelsCompress/lz4-lvl-9-4     34.08Mi ± 0%   34.14Mi ± 0%        ~ (p=0.122 n=10)
LevelsCompress/lz4-lvl-10-4    23.17Mi ± 1%   23.12Mi ± 1%        ~ (p=0.616 n=10)
LevelsCompress/lz4-lvl-11-4    23.14Mi ± 1%   23.09Mi ± 2%        ~ (p=0.223 n=10)
LevelsCompress/lz4-lvl-12-4    18.22Mi ± 1%   18.06Mi ± 1%        ~ (p=0.128 n=10)
LevelsCompress/zstd-lvl-1-4    45.34Mi ± 0%   53.50Mi ± 1%  +17.98% (p=0.000 n=10)
LevelsCompress/zstd-lvl-2-4    43.82Mi ± 1%   50.45Mi ± 1%  +15.13% (p=0.000 n=10)
LevelsCompress/zstd-lvl-3-4    36.46Mi ± 3%   38.70Mi ± 0%   +6.13% (p=0.000 n=10)
LevelsCompress/zstd-lvl-4-4    26.00Mi ± 0%   28.97Mi ± 1%  +11.43% (p=0.000 n=10)
LevelsCompress/zstd-lvl-5-4    22.08Mi ± 0%   24.28Mi ± 4%   +9.98% (p=0.000 n=10)
LevelsCompress/zstd-lvl-6-4    20.24Mi ± 1%   22.12Mi ± 0%   +9.28% (p=0.000 n=10)
LevelsCompress/zstd-lvl-7-4    20.23Mi ± 0%   22.09Mi ± 0%   +9.17% (p=0.000 n=10)
LevelsCompress/zstd-lvl-8-4    20.18Mi ± 1%   22.10Mi ± 0%   +9.52% (p=0.000 n=10)
LevelsCompress/zstd-lvl-9-4    15.29Mi ± 1%   14.77Mi ± 1%   -3.40% (p=0.000 n=10)
LevelsCompress/zstd-lvl-10-4   15.33Mi ± 0%   14.78Mi ± 1%   -3.55% (p=0.000 n=10)
LevelsCompress/zstd-lvl-11-4   7.730Mi ± 1%   8.140Mi ± 1%   +5.31% (p=0.000 n=10)
LevelsCompress/zstd-lvl-12-4   5.698Mi ± 2%   6.065Mi ± 0%   +6.44% (p=0.000 n=10)
geomean                        28.26Mi        29.32Mi        +3.74%
```

Benchmarks decompression TBD:

**Comment by fako1024** [comment]
@els0r Results look very good, performance is better across the board both in synthetic benchmarks (the results there are of course not really achievable in the wild due to the small corpus size) and in the "real world". PTAL...
