### ISSUE TITLE
CI/CD solution for goProbe

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#59]
We had drone CI in place a while back, but it crapped out and I removed it.

Shall we, for integrity's sake, re-introduce an easy to use, simple CI pipeline?

DoD

- [x] Create CI for builds / tests
- [x] Enable race detection for tests
- [x] Enable test coverage detection
- [x] Setup some CodeQL checks
- [x] Setup some basic release pipelines (e.g. `.deb` + `.rpm` packages)
- [x] Adjust badge in README.md

**Comment by fako1024** [comment]
By all means, we should enable / run / test whatever we can, whenever we can! For CI, if you want to, we could get started with one of the standard workers I'm using all around the place, e.g. here: https://github.com/fako1024/httpc/blob/main/.github/workflows/go.yml (obviously for Linux only atm). For CD, I'd love to have automated artifact generation (e.g. Debian / Fedora packages).

**Comment by els0r** [comment]
> Sidenote: We should probably fix all the remaining broken tests first... 🤣

By removing some of them 🙈

**Comment by els0r** [comment]
> By all means, we should enable / run / test whatever we can, whenever we can! For CI, if you want to, we could get started with one of the standard workers I'm using all around the place, e.g. here: https://github.com/fako1024/httpc/blob/main/.github/workflows/go.yml (obviously for Linux only atm). For CD, I'd love to have automated artifact generation (e.g. Debian / Fedora packages).

Sounds great. Let’s start based on that. I’ve never had the chance to look into artifact generation. Deos public GitHub support this or do we need to use something third party?

**Comment by fako1024** [comment]
Afaik there are runners / actions for that supported on public GitHub repos, but I haven't done it myself (yet). Maybe something along these lines: https://github.com/marketplace/actions/build-deb-action (maybe there's more general solutions, or we have to pick / decide what we want and add them manually. Would probably need a little research)...

**Comment by fako1024** [comment]
@els0r Now that the tests are fine again I've added a first shot at a CI pipeline / setup. Build + Tests are fine: https://github.com/els0r/goProbe/actions/runs/4366992848

Maybe it would make sense to require successful Actions for merge to protected branches for this repo so none of us gets any ideas in the future?

**Comment by els0r** [comment]
As discussed f2f: done :)

**Comment by fako1024** [comment]
These two packages could provide a first shot at generating `.deb` / `.rpm` packages:

- https://github.com/marketplace/actions/build-deb-action
- https://github.com/marketplace/actions/build-rpm-action

**Comment by fako1024** [comment]
@els0r OK, I think this is in a nice state now, providing:

- Continuous builds for all pushes + PRs
- Continuous tests (incl. race detection) for all pushes + PRs
- Generation of `.deb` package upon tag
- Automatic releases + upload of generated package(s) upon tag

Before looking into `.rpms` (which is a bit more tricky) I'd like to see if this pans out. Unfortunately the release part can only be tested using an actual tag, so I'd like to:

- Create a PR with the current state
- Given approval, merge it into develop
- Create a "dummy" tag (one minor version bump from the current one) or however many it needs to get it working
- Once all is good I'll manually delete the "bogus" release

Fine with you?

**Comment by els0r** [comment]
This is beyond what I imagined for
the issue so: absolutely! Thank you

**Comment by fako1024** [comment]
Alright, first successful CI run on `develop`: https://github.com/els0r/goProbe/actions/runs/4518655694. And I'm actually amazed, the full CD pipeline ran successfully on the first attempt / tag:

- Action run: https://github.com/els0r/goProbe/actions/runs/4518675687/jobs/7958701712
- Automatically created release page for `v3.0.1`: https://github.com/els0r/goProbe/releases/tag/v3.0.1

I installed the debian package on one of my hosts, works like a charm. So yay, we have CI / CD. I will create another issue to track the following:

- Automatic upload of binaries only (as suggested [here](https://github.com/els0r/goProbe/pull/86#discussion_r1148030324))
- Automatic generation of better release comment (there should be a way to create a list of all commits since the last release, a.k.a. CHANGELOG)
