### ISSUE TITLE
goProbe not shutting down gracefully

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#66]
There still seems to be an issue with the state machine somehow. I can (relatively) reliably reproduce the following behavior:

Shutdown a running instance of `goProbe` via `Ctrl-C` does not cause the state machine to terminate correctly (in fact, packets are continued to be processed - I had some debugging statements in the code that were still popping up after I sent the signal). Signal is received, but even after a while it still continues to run:
```
...
^C2023-03-06T14:29:20.333+0100	info	goProbe/goProbe.go:232	shutting down gracefully	{"app_name": "goProbe_slimcap", "app_version": "872abf81"}
...
```
I was able to abort it with a signal 6, maybe that gives a hint at where he's stuck: [abort.txt](https://github.com/els0r/goProbe/files/10898695/abort.txt)

**Comment by fako1024** [comment]
@els0r FYI.

**Comment by els0r** [comment]
> @els0r FYI.

Sh*t

**Comment by fako1024** [comment]
@els0r There were no further messages (expect for my crude `Println()` statements from within the packet population). A subsequent Ctrl-C was "successful" (as in: killed the whole thing), but that's probably not considered graceful... :stuck_out_tongue:
```
^C2023-03-06T17:00:57.513+0100	info	goProbe/goProbe.go:232	shutting down gracefully	{"app_name": "goProbe_slimcap", "app_version": "872abf81"}
Reverted flow 149.233.138.64,85.158.5.155,53,UDP (46168 / 46168)
...
^C
```

**Comment by els0r** [comment]
As mentioned in PR, I recently introduced this. Because I remember vividly that write outs were working when submitting the PR for the state machine. Will hopefully not be too hard to find (TM).

**Comment by fako1024** [comment]
Pretty sure this is the same issue as #71 now (see analysis in there).
