### ISSUE TITLE
Revisit HostID generation

### ISSUE THREAD

**Issue by els0r** [els0r/goProbe#69]
Provide means to place an identifier into the `HostID` field which uniquely identifies the system the `goDB` is stored on.

See #64 for details.

DoD

- [x] Remove dependency on external machineid package
- [x] Implement use of `/etc/machine-id` + `/var/lib/dbus/machine-id` for linux
- [x] Implement fallback random generation / storage of goDB internal ID (same format to be consistent)
- [x] Adapt logic in `goQuery` (if required)
- [x] Add tests

**Comment by els0r** [comment]
Basis of discussion
* take `/etc/machine-id`
* `/var/lib/dbus/machine-id
* goDB's own identifier

**Comment by fako1024** [comment]
@els0r Sidenote: If for some reason you don't get around to doing this in time just let me know. it seems generic enough that I can take over if requried...

**Comment by els0r** [comment]
> @els0r Sidenote: If for some reason you don't get around to doing this in time just let me know. it seems generic enough that I can take over if requried...

Howdie. I won't before the start of next week. If you want to chip at it beforehand: absolutely fine by me.

Otherwise, I'll pick it up next week

**Comment by fako1024** [comment]
@els0r I'll give it a shot...

**Comment by els0r** [comment]
> @els0r I'll give it a shot...

Thanks mate 🙏
