### ISSUE TITLE
DB summary not being written

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#7]
It seems that after the recent changes (directory restructure?), the DB summary isn't written / updated anymore. I can see the DB files getting updated, and a query yields results for e.g. the last five minutes, but the summary.json has remained unchanged since the update to the newest version of goProbe.
A quick grep in the code shows that the functions from Summary.go do not seem to be called from anywhere:
```
[fako@fako-x1 goProbe]$ grep -r DBSummary pkg/
pkg/goDB/Summary.go:type DBSummary struct {
pkg/goDB/Summary.go:func NewDBSummary() *DBSummary {
pkg/goDB/Summary.go:    summ := new(DBSummary)
pkg/goDB/Summary.go:// LockDBSummary tries to acquire a lockfile for the database summary.
pkg/goDB/Summary.go:func LockDBSummary(dbpath string) (acquired bool, err error) {
pkg/goDB/Summary.go:// LockDBSummary removes the lockfile for the database summary.
pkg/goDB/Summary.go:func UnlockDBSummary(dbpath string) (err error) {
pkg/goDB/Summary.go:func ReadDBSummary(dbpath string) (*DBSummary, error) {
pkg/goDB/Summary.go:    result := NewDBSummary()
pkg/goDB/Summary.go:            result = NewDBSummary()
pkg/goDB/Summary.go:func WriteDBSummary(dbpath string, summ *DBSummary) error {
pkg/goDB/Summary.go:func ModifyDBSummary(dbpath string, timeout time.Duration, modify func(*DBSummary) (*DBSummary, error)) (modErr error) {
pkg/goDB/Summary.go:            acquired, err := LockDBSummary(dbpath)
pkg/goDB/Summary.go:                    if err := UnlockDBSummary(dbpath); err != nil {
pkg/goDB/Summary.go:            summ, err := ReadDBSummary(dbpath)
pkg/goDB/Summary.go:                            summ = NewDBSummary()
pkg/goDB/Summary.go:            return WriteDBSummary(dbpath, summ)
pkg/goDB/Summary.go:func (s *DBSummary) Update(u InterfaceSummaryUpdate) {
```

@els0r : Did I miss something here, or is it possible that it was forgotten to adapt the calls to these updates during the restructuring?

**Comment by els0r** [comment]
@fako1024 : I cannot reproduce the issue. The summary is written in `cmd/goProbe.go` and on my machine, the summary.json file is properly updated.

Can you share the database and OS where this occurred?

**Comment by fako1024** [comment]
Can be closed, not reproducible on my end anymore either. Most likely it was caused by my upgrading the package and not properly taking into account the DB directory / paths.
