### ISSUE TITLE
Protect raw/time queries

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#75]
# v4 Release

For queries involving the `time` attribute, set default `-f` to 1 day in the past to reduce 

* load on DB
* size of output (terminal spam)

# Post-v4 Release

- [ ] Support building slices of results in special path of `DBWorkManager` for raw queries
- [ ] Consider creation extension of printer interface that supports streaming chunks of results
- [ ] ...

**Comment by els0r** [comment]
As discussed, let's make sure global-query works before we tackle this beast.
