### ISSUE TITLE
Inconsistent permissions for goDB / metadata

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#85]
It turns out that there currently is a (trivial) conflict in permission handling for data stored by `goProbe` in the `goDB`:
```
-rw------- 1 root root 232 Mar 17 10:20 .blockmeta
-rw-r--r-- 1 root root 109 Mar 17 10:20 bytes_rcvd.gpf
-rw-r--r-- 1 root root 109 Mar 17 10:20 bytes_sent.gpf
-rw-r--r-- 1 root root 144 Mar 17 10:20 dip.gpf
-rw-r--r-- 1 root root  56 Mar 17 10:20 dport.gpf
-rw-r--r-- 1 root root  73 Mar 17 10:20 pkts_rcvd.gpf
-rw-r--r-- 1 root root  73 Mar 17 10:20 pkts_sent.gpf
-rw-r--r-- 1 root root  36 Mar 17 10:20 proto.gpf
-rw-r--r-- 1 root root  37 Mar 17 10:20 sip.gpf
```

When implementing #50 I adhered to the security recommendations and set permissions for the metadata file to `0600`, while the files are still written with `0644`.
Given that traffic data can be considered sensitive I don't really think that having it limited to `0600` is such a bad idea (assuming that usually whoever runs `goProbe` is also the user doing the query, which is presumptuous of course). @els0r What do you think? We could also make this configurable (should we want to retain the option to keep access more "open)...

DoD

- [x] Make `blockmeta` more permissive
- [x] Add test
- [x] Ensure that legacy tool honors permissions

**Comment by fako1024** [comment]
@els0r Any strong feelings about this?

**Comment by els0r** [comment]
> @els0r Any strong feelings about this?

Not really. More restrictive permissions are fine. Whether we want to go as far as configuring that: not sure. We could just stick to a sensible value and leave it at that.

**Comment by fako1024** [comment]
Fine by me. So just to be sure: At OpenSystems it's _always_ `root` that calls `goQuery` (even when executed via the klicki-bunti portal)?

**Comment by els0r** [comment]
Not always. There may be cases where non-root runs the query.

**Comment by fako1024** [comment]
As discussed, we keep it more permissive and switch `blockmeta` to `0644`.
