### ISSUE TITLE
Improve CI / CD pipeline

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#90]
With #59 we have a great basis for CI / CD already. However, there are a few things that could be improved:

- [x] Removal of dummy tag `v3.0.1`
- [x] Automatic upload of binaries only (as suggested [here](https://github.com/els0r/goProbe/pull/86#discussion_r1148030324))
- [x] Automatic generation of better release comment (there should be a way to create a list of all commits since the last release, a.k.a. CHANGELOG)
- [x] Build / upload of `rpm` packages (and binaries for Fedora / CentOS)
- [x] Cross-check if tags (bug/feature) can be used in action, otherwise enforce
- [x] Add PR naming rule action
- [x] Re-test CD / release and confirm correct output

**Comment by fako1024** [comment]
@els0r FYI. Regarding the first point. Once you've had a look at the results from #59 (see last comment) feel free to delete the tag if you like (as it only served as a test for CD).

**Comment by fako1024** [comment]
@els0r FYI: I just deleted the test release & tag v3.0.1 from the repo (we'll try another one once the changes in this issue are complete to test if rpm + binary + CHANGELOG generation are working properly)...

**Comment by fako1024** [comment]
@els0r This is what the CHANGELOG looks like now: https://github.com/els0r/goProbe/releases/tag/v3.0.2 . PR #92 should fix the missing packages / binaries.

**Comment by fako1024** [comment]
@els0r One more attempt (sorry for that, it's really tricky to deploy this without ready-to use examples / snippets and only see the outcome upon tagging) :see_no_evil: : #95

**Comment by fako1024** [comment]
I'm afraid the release note generation does not feature the inclusion of issue labels (it simply uses the GitHub automatic generation logic that's also used when manually creating a release and clicking on "Generate release notes" - there are not options to include labels on that API).

However, we _can_ enforce PR titles, there is an action for that: https://github.com/marketplace/actions/pull-request-title-rules - allowing us to pretty much do what we need. Given our requirements I'd suggest the following config / rules:
```
    regex: '^\[(feature|bugfix)\] [A-Z].+'       # Regex the title should match.
    allowed_prefixes: '\[feature\],\[bugfix\]'   # Title should start with the given prefix (probably redundant to regex, but just making sure)
    prefix_case_sensitive: true                  # Title prefix are case insensitive
    min_length: 32                               # Min length of the title
    max_length: 256                              # Max length of the title
```

(Start with [feature] / [bugfix], followed by a single whitespace, then an uppercase letter, then whatever you want, up to 256 characters).

@els0r What do you think? Do we need any further categories?

**Comment by els0r** [comment]
I'm on board with the tags and also that we solve capitalization once and for all  (at least for the title 😎). What about the `doc` and `trivial` tag? Even though the last one is a playing field for abuse. I do wish to believe that we're adults every once in a while though.

**Comment by fako1024** [comment]
@els0r Sounds reasonable (including the `trivial` tag - We've been holding it together so far across different time zones, I'm sure we can handle a potentially abuse tag :wink: ). I'd add `security` to the list (for obvious reasons), which leaves us with this (I've removed the individual prefix rule because I have to use the scripted variant anyway, so one way of enforcing is enough):
```
    regex: '^(\[(feature|bugfix|doc|security|trivial)\])+ [A-Z].+'       # Regex the title should match.
    min_length: 32                               # Min length of the title
    max_length: 256                              # Max length of the title
```
One more thing: Should we rename the `enhancement` GitHub label to match `feature` for consistency?

**Comment by els0r** [comment]
> One more thing: Should we rename the `enhancement` GitHub label to match `feature` for consistency?

Done.

As for `security`: good point, let's add.

**Comment by fako1024** [comment]
@els0r Alright, I think we're good here. Final test successful (of course it contains a lot of PRs that didn't follow the new ruleset, but you get the idea): https://github.com/els0r/goProbe/releases/tag/v3.0.4

If you concur I'll delete the test tag one last time and close this issue...
