### ISSUE TITLE
Assess reasonable ring buffer sizes

### ISSUE THREAD

**Issue by fako1024** [els0r/goProbe#98]
In order to choose optimal / better buffer sizes we should somehow measure the necessary footprint.

Details TBD...

**Comment by fako1024** [comment]
Some findings: https://github.com/els0r/goProbe/issues/74#issuecomment-1606126044

**Comment by els0r** [comment]
From repeating the test with latest version (`ef516169`) on https://github.com/els0r/goProbe/issues/74: a `buffer_size` of `1048576` on external interfaces and `524288` on tunnel interfaces, `block_size` of 4 on all interfaces, there are no drops.

An exception is right after a writeout on a high-throughput host (see https://github.com/els0r/goProbe/issues/149).
